sprint 3
Krynegal/url_shortener pull request #17
Opened 2022-08-08 17:20 UTC by Krynegal

2022-08-11 16:48 UTC, capsulated requested changes
В целом всё очень классно!

Добавил несколько коментов.

Также, посмотреть, где переменная **err** создаётся по-новой с помощью конcтрукции `err :=`. Там где можно, лучше переиспользовать существующую переменную **err**. Мелочь, конечно, для памяти, но всё же

2022-08-11 16:48 UTC, capsulated commented on internal/handlers/handlers.go
> +	db, err := sql.Open("postgres", h.Config.DB)
Эту логику лучше перенести в пакет storage в структуру DB. А в хендлер передать указатель на storage. 

Тут получается мы создаём новое соединение. А лучше проверить текущее соединение. Вариантов несколько:
- в существующем соединении выполнить SELECT 1
- *pg.DB.Closed() == true ?
- db.PoolStats()  > 1
- и тп

Какое из них правильное не подскажу)

2022-08-11 16:48 UTC, capsulated commented on internal/storage/postgres/postgres.go
> +func NewPostgresDB(dataSourceName string) (*sql.DB, error) {
А стоит его выносить в отдельный пакет-то? 

Мне кажется если перенести в db_storage в конструктор NewDB, то будет удобнее 🤔

Или это для определённых целей сделано?

2022-08-11 16:48 UTC, capsulated commented on internal/storage/storage.go
> +		postgresDB, err := postgres.NewPostgresDB(cfg.DB)
Я бы его NewPostgresStorage назвал бы, по аналогии NewFileStorage. Или вообще NewDatabaseStorage с интерфейсом, чтобы БД ещё можно было бы заменить в случае необходимости 😊

2022-08-13 10:59 UTC, Krynegal commented on internal/handlers/handlers.go
> +	db, err := sql.Open("postgres", h.Config.DB)
Разве PingContext() не походит для проверки соединения?

2022-08-15 20:44 UTC, capsulated commented on internal/handlers/handlers.go
> +	db, err := sql.Open("postgres", h.Config.DB)
Это относиться к пункту "- и тп" )))

sql.Open не подходит)

2022-08-15 20:56 UTC, capsulated approved these changes
👍🔥

2022-08-16 14:52 UTC, merged