increment 14
Krynegal/url_shortener pull request #18
Opened 2022-08-21 18:04 UTC by Krynegal

2022-08-24 19:25 UTC, capsulated requested changes
Всё супер! 🔥👍

Но может всё же добавить **fanIn** и **batch** update 🥺 ?

2022-08-24 19:25 UTC, capsulated commented on internal/storage/db_storage.go
>  	Storager
🔥

2022-08-24 19:25 UTC, capsulated commented on internal/storage/db_storage.go
>  	Storager
**Extended** структура)

2022-08-24 19:25 UTC, capsulated commented on internal/storage/db_storage.go
> +	_, err = db.db.Exec("UPDATE URLS SET deleted=true WHERE url_id = ($1) AND created_by = ($2);", urlStrID, uid)
В PostgresSQL вроде можно и не добавлять скобочки для значений...

2022-08-24 19:25 UTC, capsulated commented on internal/storage/db_storage.go
> +	_, err = db.db.Exec("UPDATE URLS SET deleted=true WHERE url_id = ($1) AND created_by = ($2);", urlStrID, uid)
А как же **fanIn** и **batch update** 🥺

2022-08-24 19:26 UTC, capsulated requested changes
Всё супер! 🔥👍

Но может всё же добавить **fanIn** и **batch** update 🥺 ?

2022-08-25 18:55 UTC, Krynegal commented on internal/storage/db_storage.go
>  	Storager
Плохая практика засовывать интерфейс в интерфейс?)
Так вроде изолированность сохраняется

2022-08-26 15:29 UTC, capsulated commented on internal/storage/db_storage.go
>  	Storager
Нет-нет, как раз именно так и нужно! 

Как раз в **go** именно так реализуется расширение интерфейсов - через встраивание

2022-08-26 16:44 UTC, capsulated approved these changes
Есть возможность его доработать, если есть желание. Один из вариантов такой:
- Создать отдельную структуру, что-то типа `BatchUpdater` (можно в пакете handlers или storage)
- В ней создать буфер и канал
- Буфер накапливает значения из разных запросов до определённой емкости (10/20/50/100 до разумных пределов)
- И по наступлению нужных условий вызываем в этом воркере метод DbStorage.Delete, который одном запросом это обновляет

2022-08-26 16:44 UTC, capsulated commented on internal/handlers/handlers.go
> +var deleteURLCh = make(chan job, 3)
Я бы сделал отдельную структуру, и всё же лучше в отдельном пакете. И передать указатель на неё в хендлер

2022-08-26 16:44 UTC, capsulated commented on internal/handlers/handlers.go
> +		buffer = make([]int, 0, 3)
А почему слайс с capacity именно на 3 значения? )))

2022-08-26 16:44 UTC, capsulated commented on internal/handlers/handlers.go
> +	go func() {
🤔 В принципе, задание реализовано, да)

2022-08-27 07:12 UTC, merged